[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
